# This file was generated by GoReleaser. DO NOT EDIT.
cask "c3p" do
  version "1.0.6"

  on_macos do
    on_intel do
      sha256 "028f3b3a76054a59e77ed0a30175a7ca15467147615a61daca86a1752e3a5639"
      url "https://github.com/htxryan/claude-code-config-profiles/releases/download/v#{version}/c3p_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "667a1548d0ee855e36be3163eeef9c0095da0c7374722bb3b62af983c52556e5"
      url "https://github.com/htxryan/claude-code-config-profiles/releases/download/v#{version}/c3p_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "871c3681d843fc8f28af996a13c65aa41068f00f16f4b723a0337d40e77b3cab"
      url "https://github.com/htxryan/claude-code-config-profiles/releases/download/v#{version}/c3p_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d000b2fcf7c2aa94fe1b76a02238a5246ddfd0235584400e1d3fb5926e870b4"
      url "https://github.com/htxryan/claude-code-config-profiles/releases/download/v#{version}/c3p_#{version}_linux_arm64.tar.gz"
    end
  end

  name "c3p"
  desc "Swappable .claude/ configuration profiles for Claude Code projects"
  homepage "https://github.com/htxryan/claude-code-config-profiles"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c3p"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/c3p"]
  end

  # No zap stanza required

end
