# This file was generated by GoReleaser. DO NOT EDIT.
cask "c3p" do
  version "1.0.4"

  on_macos do
    on_intel do
      sha256 "2fa8d9665ba9f2ba96c7de0f7aa3e126dae30df15c2a18a2058798ac5c77ca1a"
      url "https://github.com/htxryan/claude-code-config-profiles/releases/download/v#{version}/c3p_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a54fd6eef59f2c50979705af7ef83feb975abd50b3c14784f68e0c10e5e7e0e2"
      url "https://github.com/htxryan/claude-code-config-profiles/releases/download/v#{version}/c3p_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "99e646fd70d7a9f4786b2166aa6ef6d510e1183c09bddc1e77ddb79f2ea3651d"
      url "https://github.com/htxryan/claude-code-config-profiles/releases/download/v#{version}/c3p_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "474f2380fe1b3902bcba45110432d2c9aff1bfc519fa28229cf11ac256991af1"
      url "https://github.com/htxryan/claude-code-config-profiles/releases/download/v#{version}/c3p_#{version}_linux_arm64.tar.gz"
    end
  end

  name "c3p"
  desc "Swappable .claude/ configuration profiles for Claude Code projects"
  homepage "https://github.com/htxryan/claude-code-config-profiles"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c3p"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/c3p"]
  end

  # No zap stanza required

end
