# This file was generated by GoReleaser. DO NOT EDIT.
cask "c3p" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "5d0db9f0243053470ffd2fedd3d358393d5978ea68133a2f3723ea88009e5907"
      url "https://github.com/htxryan/claude-code-config-profiles/releases/download/v#{version}/c3p_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6158ab70f76d1ccce08cdbf47c34dafd9b673056a74c95f2f5ba71af441ef69e"
      url "https://github.com/htxryan/claude-code-config-profiles/releases/download/v#{version}/c3p_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ea6a3c40943553e6cd36ea4fe3f959d0a1091ae7aa789f24f8d8ac946d3e2526"
      url "https://github.com/htxryan/claude-code-config-profiles/releases/download/v#{version}/c3p_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cd81e53ea1e672f1c5b94c09f9356459a2c5c0e30d0e44eb169cff219876edd2"
      url "https://github.com/htxryan/claude-code-config-profiles/releases/download/v#{version}/c3p_#{version}_linux_arm64.tar.gz"
    end
  end

  name "c3p"
  desc "Swappable .claude/ configuration profiles for Claude Code projects"
  homepage "https://github.com/htxryan/claude-code-config-profiles"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c3p"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/c3p"]
  end

  # No zap stanza required

end
